# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.2
  common-tools: onimur/common-tools@0.0.3
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - common-tools/persist-dir:
          paths: .next 
      - common-tools/persist-dir:
          paths: out 
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    
    jobs:
      - example-job
      - hold:
          type: approval
          filters:
            branches:
              only: main
        - node/run:
          pkg-manager: yarn
          name: build
          yarn-run: build  
        - node/run:
          pkg-manager: yarn
          name: export
          yarn-run: export
      - node/run:
          pkg-manager: yarn
          name: deploy
          yarn-run: deploy
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '16.10'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: yarn
