# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.2
  github-cli: circleci/github-cli@2.1.0

# Invoke jobs via workflows
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - github-cli/setup:
          token: GITHUB_TOKEN
  deploy:
    docker:
      # replace with your preferred image
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - attach_workspace:
          at: out
      - name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "zulfikarfahmi38@gmail.com"
            git config user.name "falakh"
      - add_ssh_keys:
          fingerprints:
            - "bb:41:6a:6d:4c:32:f1:df:e7:54:26:0f:0b:99:74:7b"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist out
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only: main
      - node/run:
          pkg-manager: yarn
          name: deploy
          yarn-run: deploy
          requires:
            - hold  
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '16.10'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: yarn
