# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1


orbs:
  node: circleci/node@5.0.2
  github-cli: circleci/github-cli@2.1.0

jobs:
  build:
    docker:
      - image: 'cimg/node:16.15.0'
    steps:
      - checkout
      - run: echo "Build started on `date`"                     
      - node/install-packages:
          check-cache: detect # try using yarn.lock
      - run: yarn run build 
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: out
          # Must be relative path from root
          paths: .
  deploy:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - attach_workspace:
          at: out
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "zulfikarfahmi38@gmail.com"
            git config user.name "falakh"
      - add_ssh_keys:
          fingerprints:
            - "bb:41:6a:6d:4c:32:f1:df:e7:54:26:0f:0b:99:74:7b"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist out
workflows:
  sample: 
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only: main
      - build:
          requires:
            - hold 
      - deploy:
          requires:
              - build 
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '16.10'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: yarn
